language: node_js

node_js: '0.10'

cache:
  directories:
  - ~/.npm
  - ~/.cache

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install jshint bower karma-cli --global --quiet
- npm install --quiet
- bower install --quiet

script:
- jshint . -e .json
- karma start karma.conf.js --browsers=PhantomJS,Firefox

deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: "bzEoEA3Vbu5p4c9fot6BabEL1vhuH9VT2cDCLxou4SvJ+YN7FM14ZzP6dQg22tjL6TBK8y33Ivohrt+ryw8pLyb8/IMJd5/N5nJGYBxj3jjUM3FoYJwNaAFVPYiKIpKyC9B0kVhTZ8j+quwx74zRyjud9Hr271V14JHiK5RESNg="
  on:
    tags: true
